# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  catalog.db: 
    image: mongo
  
  basket.db:
    image: redis:alpine

  discount.db:
    image: postgres
  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce

  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: basket.api
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.api:
    image: discount.api

    build: 
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile
volumes:
  mongo_data: 
  portainer_data:
  postgres_data:
  pgadmin_data:

